### ISSUE TITLE
RDBMS 설계

### ISSUE THREAD

**Issue by kdwhan** [2017-Capstone-2nd-Viewreful-Team-12/Master#2]
RDBMS 설계 완료. 검토 부탁드립니다!
대부분 회의 내용을 기반으로 설계하였고 IssueType과 AnalysisResultDynamic과의 관계가 필요하다고 판단하여 N:M 관계를 추가하였는데 맞는지 잘 모르겠습니다.

**Comment by kmu-yoonsh** [comment]
[https://github.com/2017-Capstone-2nd-Viewreful-Team-12/Master/blob/master/doc/Database/RDBMS/viewreful_DB_design.PNG](url)

**Comment by kmu-yoonsh** [comment]
테이블의 정규화를 깨뜨릴 부분이 많지 않아 보입니다. 
NoSQL에서는 아래와 같이 하면 어떨까요? 
// Professor
 
{
            "_id" : ObjectId("..."),
            "name" : "..."
}
 
// Lecture
 
{
            "_id" : ObjectId("..."),
            "name" : "...",
 
            // Professor_has_Lecture
            "professors" : [ ObjectId("..."),         ... ]
}
 
// Student
 
{
            "_id" : ObjectId("..."),
            "professorId" : ObjectId("..."),

            // Student_has_Lecture
            "lectures" : [ ObjectId("..."), ... ]
}
 
// Problem
 
{
            "_id" : ObjectId("..."),
            // Student_has_Problem
            "students" : [ ObjectId("..."),           ... ]
 
}
 
// AnalysisResultStatic
{
            _id : ObjectId("..."),
            sequence : 0,
            _problems: [ ObjectId("..."), ... ]
}
 
// AnalysisResultStatic
{
            "_id" : ObjectId("..."),
            "problems": [ ObjectId("..."), ... ]
}
 
// AnalysisResultDynamic
{
            "_id" : ObjectId("..."),
            "row" : 0,
            "column" : 0,
            "staticId" : ObjectId("..."),
            "staticResults" : [ ObjectId("..."), ... ]
            // AnalysisResultDynamic_has_IssueType
            "issueTypes" : [ ObjectId("..."), ...]
}
 
 
 
 
// IssueType
 
{
            "_id" : ObjectId("..."),
            "korean" : "...",
            "english" : "...",
            "toolId" : ObjectId("...")
}
 
// AnalysisTool
 
{
            "_id" : ObjectId("..."),
            "name" : "..."
}

**Comment by palace2001** [comment]
감사합니다! 반영해보겠습니다.
