### ISSUE TITLE
파이썬 기반의 스크립트 언어에 대한 리팩토링

### ISSUE THREAD

**Issue by bonopi07** [2017-Capstone-2nd-Viewreful-Team-12/Master#5]
현재까지의 스크립트는 기능 유지 및 코드 최적화에 비중을 두었으며, 다음과 같은 코드의 추가적인 리팩토링이 필요함.
1. 객체지향적 소스코드(클래스화)
2. 수정중인 database에 대한 스키마 미적용(현재는 임의의 test data나 파싱 기술을 사용하였음)
3. 함수 당 20line 이하로 작성

**Comment by bonopi07** [comment]
1. 수정중인 database의 스키마를 아직 전달받지 못하여서 적용되지 않음.
2. 임의로 구성한 example data file을 실행하여 정상 작동 확인 완료. (서버에서가 아닌 내부 스크립트 실행 상태 확인)
3. 코드의 클래스화, 함수의 라인 최적화 진행 완료.

**Comment by kdwhan** [comment]
https://github.com/2017-Capstone-2nd-Viewreful-Team-12/Master/blob/master/doc/Database/RDBMS/viewreful_DB_design.PNG
